"""empty message

Revision ID: 4be54046a2d1
Revises: c0d1e71acda
Create Date: 2015-07-01 17:11:01.251040

"""

# revision identifiers, used by Alembic.
revision = '4be54046a2d1'
down_revision = 'c0d1e71acda'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniqueid', sa.String(), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('arrive', sa.DateTime(), nullable=True),
    sa.Column('beginexp', sa.DateTime(), nullable=True),
    sa.Column('endexp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'uniqueid')
    )
    op.drop_table('results')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'results_pkey')
    )
    op.drop_table('participant')
    ### end Alembic commands ###
