"""empty message

Revision ID: 2c04cd102dea
Revises: 
Create Date: 2017-03-21 16:29:42.259575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c04cd102dea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('browser', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('exp_name', sa.String(length=32), nullable=False),
    sa.Column('begin_session', sa.DateTime(), nullable=False),
    sa.Column('begin_experiment', sa.DateTime(), nullable=True),
    sa.Column('results', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('BART',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.Column('trial_action_num', sa.Integer(), nullable=True),
    sa.Column('user_action', sa.Integer(), nullable=True),
    sa.Column('pumps', sa.Integer(), nullable=True),
    sa.Column('pop_point', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('distribution', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('category_switch',
    sa.Column('cs_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=2), nullable=True),
    sa.Column('reaction_time', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('block', sa.String(length=200), nullable=True),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('user_answer', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('cs_id')
    )
    op.create_table('event_data',
    sa.Column('ev_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('exp_name', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('interval', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('ev_id')
    )
    op.create_table('keep_track',
    sa.Column('kt_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.Column('reaction_time', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.String(length=32), nullable=True),
    sa.Column('block', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_words', sa.String(length=100), nullable=True),
    sa.Column('input_words', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('kt_id')
    )
    op.create_table('question_data',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('exp_name', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.String(length=32), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('distraction', sa.String(length=32), nullable=True),
    sa.Column('openended', sa.Unicode(length=32), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_data')
    op.drop_table('keep_track')
    op.drop_table('event_data')
    op.drop_table('category_switch')
    op.drop_table('BART')
    op.drop_table('session')
    op.drop_table('participant')
    # ### end Alembic commands ###
