"""empty message

Revision ID: c908d29b193d
Revises: 43c800fdf0c8
Create Date: 2016-08-11 15:24:09.241984

"""

# revision identifiers, used by Alembic.
revision = 'c908d29b193d'
down_revision = '43c800fdf0c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BART',
    sa.Column('bart_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('bart_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BART')
    ### end Alembic commands ###
