"""empty message

Revision ID: ce931226a485
Revises: c908d29b193d
Create Date: 2016-08-11 15:33:16.934887

"""

# revision identifiers, used by Alembic.
revision = 'ce931226a485'
down_revision = 'c908d29b193d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BART', sa.Column('balloon_num', sa.Integer(), nullable=True))
    op.add_column('BART', sa.Column('pop_point', sa.Integer(), nullable=True))
    op.add_column('BART', sa.Column('pumps', sa.Integer(), nullable=True))
    op.add_column('BART', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('BART', sa.Column('user_action', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BART', 'user_action')
    op.drop_column('BART', 'timestamp')
    op.drop_column('BART', 'pumps')
    op.drop_column('BART', 'pop_point')
    op.drop_column('BART', 'balloon_num')
    ### end Alembic commands ###
