"""empty message

Revision ID: f496302470a5
Revises: None
Create Date: 2016-06-22 19:22:38.446699

"""

# revision identifiers, used by Alembic.
revision = 'f496302470a5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keep_track',
    sa.Column('kt_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.Column('reaction_time', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.String(length=32), nullable=True),
    sa.Column('block', sa.Unicode(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_words', sa.Unicode(length=32), nullable=True),
    sa.Column('input_words', sa.Unicode(length=32), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('kt_id')
    )
    op.create_table('question_data',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('gfg_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('exp_name', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.String(length=32), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('distraction', sa.String(length=32), nullable=True),
    sa.Column('openended', sa.Unicode(length=32), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_data')
    op.drop_table('keep_track')
    ### end Alembic commands ###
