"""empty message

Revision ID: 19fe9d698cd6
Revises: None
Create Date: 2015-11-25 23:07:26.046332

"""

# revision identifiers, used by Alembic.
revision = '19fe9d698cd6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('gfgid', sa.String(), nullable=False),
    sa.Column('browser', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('debug', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('exp_name', sa.String(), nullable=False),
    sa.Column('begin_session', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('store_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfgid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_switch',
    sa.Column('cs_id', sa.Integer(), nullable=False),
    sa.Column('gfgid', sa.String(), nullable=False),
    sa.Column('sess_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=2), nullable=False),
    sa.Column('reaction_time', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('block', sa.String(length=20), nullable=False),
    sa.Column('question', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.String(length=20), nullable=False),
    sa.Column('user_answer', sa.String(length=20), nullable=False),
    sa.Column('beginexp', sa.DateTime(), nullable=False),
    sa.Column('endexp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sess_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('cs_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_switch')
    op.drop_table('store_user')
    op.drop_table('session')
    ### end Alembic commands ###
