"""empty message

Revision ID: 1de1de2ef14b
Revises: None
Create Date: 2015-12-05 19:49:57.263411

"""

# revision identifiers, used by Alembic.
revision = '1de1de2ef14b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_switch',
    sa.Column('cs_id', sa.Integer(), nullable=False),
    sa.Column('gfgid', sa.String(), nullable=False),
    sa.Column('sess_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=2), nullable=True),
    sa.Column('reaction_time', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('block', sa.Unicode(), nullable=True),
    sa.Column('question', sa.Unicode(), nullable=True),
    sa.Column('answer', sa.Unicode(), nullable=True),
    sa.Column('user_answer', sa.Unicode(), nullable=True),
    sa.Column('beginexp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sess_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('cs_id')
    )
    op.drop_table('exp__category_switch')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exp__category_switch',
    sa.Column('cs_id', sa.INTEGER(), nullable=False),
    sa.Column('gfgid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sess_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trial_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('reaction_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('block', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('beginexp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sess_id'], [u'session.session_id'], name=u'exp__category_switch_sess_id_fkey'),
    sa.PrimaryKeyConstraint('cs_id', name=u'exp__category_switch_pkey')
    )
    op.drop_table('category_switch')
    ### end Alembic commands ###
