"""empty message

Revision ID: 2674645403ab
Revises: None
Create Date: 2015-12-13 23:26:00.549336

"""

# revision identifiers, used by Alembic.
revision = '2674645403ab'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keep_track',
    sa.Column('kt_id', sa.Integer(), nullable=False),
    sa.Column('gfgid', sa.String(), nullable=False),
    sa.Column('sess_id', sa.Integer(), nullable=True),
    sa.Column('trial_num', sa.Integer(), nullable=True),
    sa.Column('reaction_time', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.String(), nullable=True),
    sa.Column('block', sa.Unicode(), nullable=True),
    sa.Column('beginexp', sa.DateTime(), nullable=True),
    sa.Column('target_word1', sa.String(), nullable=True),
    sa.Column('target_word2', sa.String(), nullable=True),
    sa.Column('target_word3', sa.String(), nullable=True),
    sa.Column('target_word4', sa.String(), nullable=True),
    sa.Column('target_word5', sa.String(), nullable=True),
    sa.Column('input_word1', sa.String(), nullable=True),
    sa.Column('input_word2', sa.String(), nullable=True),
    sa.Column('input_word3', sa.String(), nullable=True),
    sa.Column('input_word4', sa.String(), nullable=True),
    sa.Column('input_word5', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sess_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('kt_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keep_track')
    ### end Alembic commands ###
