"""empty message

Revision ID: 2a5c8481beca
Revises: None
Create Date: 2015-12-12 00:28:27.225017

"""

# revision identifiers, used by Alembic.
revision = '2a5c8481beca'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_data',
    sa.Column('ev_id', sa.Integer(), nullable=False),
    sa.Column('gfgid', sa.String(), nullable=False),
    sa.Column('sess_id', sa.Integer(), nullable=True),
    sa.Column('exp_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('value_1', sa.String(), nullable=True),
    sa.Column('value_2', sa.String(), nullable=True),
    sa.Column('value_3', sa.String(), nullable=True),
    sa.Column('interval', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sess_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('ev_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_data')
    ### end Alembic commands ###
