"""empty message

Revision ID: 4477fda6aea8
Revises: None
Create Date: 2015-10-21 18:36:45.629102

"""

# revision identifiers, used by Alembic.
revision = '4477fda6aea8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('gfgid', sa.String(), nullable=True))
    op.drop_column('participant', 'uniqueid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('uniqueid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('participant', 'gfgid')
    ### end Alembic commands ###
