"""empty message

Revision ID: 47b887379cde
Revises: None
Create Date: 2015-10-30 15:43:31.113552

"""

# revision identifiers, used by Alembic.
revision = '47b887379cde'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_switch', sa.Column('block', sa.String(length=20), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_switch', 'block')
    ### end Alembic commands ###
