"""empty message

Revision ID: 525e77b3aae0
Revises: None
Create Date: 2015-11-06 00:24:16.113997

"""

# revision identifiers, used by Alembic.
revision = '525e77b3aae0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfgid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_user')
    ### end Alembic commands ###
