"""empty message

Revision ID: 6d962ad1c33
Revises: None
Create Date: 2015-10-30 15:15:43.952424

"""

# revision identifiers, used by Alembic.
revision = '6d962ad1c33'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_switch',
    sa.Column('cs_id', sa.Integer(), nullable=False),
    sa.Column('gfgid', sa.String(), nullable=False),
    sa.Column('sess_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=2), nullable=False),
    sa.Column('reaction_time', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.String(length=20), nullable=False),
    sa.Column('user_answer', sa.String(length=20), nullable=False),
    sa.Column('beginexp', sa.DateTime(), nullable=False),
    sa.Column('endexp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sess_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('cs_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_switch')
    ### end Alembic commands ###
