"""empty message

Revision ID: 935dcc07b67
Revises: None
Create Date: 2015-11-30 00:04:02.975198

"""

# revision identifiers, used by Alembic.
revision = '935dcc07b67'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_switch', sa.Column('trial_num', sa.Integer(), nullable=True))
    op.alter_column('category_switch', 'answer',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('category_switch', 'beginexp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('category_switch', 'block',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('category_switch', 'question',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('category_switch', 'reaction_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('category_switch', 'response',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('category_switch', 'user_answer',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('category_switch', 'endexp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_switch', sa.Column('endexp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('category_switch', 'user_answer',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('category_switch', 'response',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('category_switch', 'reaction_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('category_switch', 'question',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('category_switch', 'block',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('category_switch', 'beginexp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('category_switch', 'answer',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('category_switch', 'trial_num')
    ### end Alembic commands ###
